ozgur_etkinlik/auths/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="user-login"),
    path('logout/', views.user_logout, name="user-logout"),
]

ozgur_etkinlik/events/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('', views.event_list, name="event-list"),
    path('event-create/', views.event_create, name="event-create"),
    path('profile/', views.profile, name="profile"),
    path('event-update/<slug:slug>', views.event_update, name="event-update"),
    path('event-delete/<slug:slug>', views.event_delete, name="event-delete"),
    path('event-detail/<slug:slug>', views.event_detail, name="event-detail"),
    path('registerEvent/<int:id>', views.registerEvent, name="registerEvent"),

    url(r'^new-add-comment/(?P<pk>[0-9]+)/(?P<model_type>[\w]+)/$', views.new_add_comment, name='new-add-comment'),

    url(r'^get-child-comment-form/$', views.get_child_comment_form, name='get-child-comment-form'),

]

ozgur_etkinlik/ozgur_etkinlik/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from events import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('auths/', include('auths.urls')),
    path('accounts/', include('allauth.urls')),
    path('', views.index, name="index"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ozgur_etkinlik/events/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify, safe
from unidecode import unidecode
from uuid import uuid4
from django.shortcuts import reverse
from location_field.models.plain import PlainLocationField
import os

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


def upload_to(instance, filename):
    uzanti = filename.split('.')[-1]
    new_name = "%s.%s" % (str(uuid4()), uzanti)
    unique_id = instance.unique_id
    return os.path.join('event', unique_id, new_name)


class Event(models.Model):
    CATEGORY = (
        (None, 'Lütfen Seçiniz'), ('diğer', 'DİĞER'), ('yazılım', 'YAZILIM'), ('grafik tasarım', 'GRAFIK TASARIM'))

    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar", default=1)
    title = models.CharField(max_length=50, verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    starter_date = models.DateField(null=True, blank=True, verbose_name='Başlangıç günü')
    starter_time = models.TimeField(null=True, verbose_name='Başlangıç saati')
    size = models.IntegerField(verbose_name='Katılımcı sayısı', null=True, default=0)
    city = models.CharField(max_length=255, null=True)
    location = PlainLocationField(based_fields=['City'], zoom=7, null=True)
    slug = models.SlugField(null=True, unique=True, editable=False, verbose_name='Slug')
    category = models.CharField(choices=CATEGORY, blank=True, null=True, max_length=53, verbose_name='Kategori')
    image = models.ImageField(default='default/marijuana.jpg', verbose_name='Resim', upload_to=upload_to,
                              null=True, help_text='Kapak Fotoğrafı Yükleyiniz', blank=True)

    def __str__(self):
        return self.title

    def get_come_event_count(self):
        etkinlige_gelen = self.event_member.count()
        return etkinlige_gelen

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'slug': self.slug})

    def get_come_event_object(self):
        data_list = []
        qs = self.event_member.all()
        for obj in qs:
            data_list.append(obj.user)
        return data_list

    def get_image(self):
        if self.image:
            return self.image.url
        else:
            return '/media/default/marijuana.jpg'

    def get_unique_slug(self):
        sayi = 0
        slug = slugify(unidecode(self.title))
        new_slug = slug
        while Event.objects.filter(slug=new_slug).exists():
            sayi += 1
            new_slug = "%s-%s" % (slug, sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            self.unique_id = str(uuid4())
            self.slug = self.get_unique_slug()
        else:
            event = Event.objects.get(slug=self.slug)
            if event.title != self.title:
                self.slug = self.get_unique_slug()

        super(Event, self).save(*args, **kwargs)

    def get_event_new_comment(self):
        content_type = ContentType.objects.get_for_model(self)
        object_id = self.id
        all_comment = NewComment.objects.filter(content_type=content_type, object_id=object_id)
        return all_comment

    def get_event_comment_count(self):
        return len(self.get_event_new_comment())


class EventMember(models.Model):
    user = models.ForeignKey(User, null=True, default=1, related_name='event_member', on_delete=True)
    event = models.ForeignKey(Event, null=True, on_delete=True, related_name='event_member')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi", null=True)

    class Meta:
        verbose_name_plural = 'Etkinliğe gelen katılımcılar'

    def __str__(self):
        return "{} {}".format(self.user, self.event)


class NewComment(models.Model):
    user = models.ForeignKey(User, null=True, default=1, related_name='+', on_delete=True)
    is_parent = models.BooleanField(default=False)

    content_type = models.ForeignKey(to=ContentType, null=True, on_delete=True)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    icerik = models.TextField(verbose_name='Yorum', max_length=1000, blank=False, null=True)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        username = self.user.username
        text = "{0} {1}".format(username, self.content_type.model)
        return text

    class Meta:
        verbose_name_plural = "İç içe yorum sistemi"

    @classmethod
    def add_comment(cls, nesne, model_type, user, icerik):
        content_type = ContentType.objects.get_for_model(nesne.__class__)
        cls.objects.create(user=user, icerik=icerik, content_type=content_type, object_id=nesne.pk)
        if model_type == 'comment':
            nesne.is_parent = True
            nesne.save()

    def get_child_comment(self):
        if self.is_parent:
            content_type = ContentType.objects.get_for_model(self.__class__)
            all_child_comment = NewComment.objects.filter(content_type=content_type, object_id=self.pk)
            return all_child_comment
        return None

ozgur_etkinlik/events/forms.py
from django import forms
from .models import Event, NewComment


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ["user", "title", "content", "image", 'category', "starter_date", 'starter_time', 'city', 'location']

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)  # kalıtım aldığı init fonksiyonları
        for field in self.fields:
            # print(field, self.fields[field])
            self.fields[field].widget.attrs = {'class': 'form-control'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = NewComment
        fields = ['icerik']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control'}


class SearchForm(forms.Form):
    TIME = [('any_date', 'Herhangi bir tarih'), ('today', 'Bugün'), ('tomorrow', 'Yarın'), ('tomorrow', 'Yarın'),
            ('this_weekend', 'Bu haftasonu'), ('this_week', 'Bu hafta'), ('next_week', 'Gelecek hafta'),
            ('this_mounth', 'Bu ay'), ('next_mounth', 'Gelecek ay')]

    search = forms.CharField(required=False, max_length=500,
                             widget=forms.TextInput(attrs={'placeholder': 'Event',
                                                           'class': 'form-control'}))
    location = forms.CharField(required=False, max_length=50,
                               widget=forms.TextInput(attrs={'placeholder': 'Location',
                                                             'class': 'form-control'}))
    time = forms.ChoiceField(label='', widget=forms.Select(attrs={'class': 'form-control'}),
                             choices=TIME, required=False)

ozgur_etkinlik/events/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, Http404
from django.http import HttpResponseForbidden
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Event, EventMember, NewComment
from .forms import EventForm, CommentForm

from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth.decorators import login_required
from .forms import SearchForm

from django.urls import reverse_lazy


# Create your views here.

def index(request):
    return render(request, 'index.html')


def event_list(request):
    form = SearchForm(data=request.GET or None)
    events = Event.objects.all()
    page = request.GET.get('page', 1)

    if form.is_valid():
        search = form.cleaned_data.get('search', None)
        location = form.cleaned_data.get('location', None)
        # time = form.cleaned_data.get('time', None)
        if search:
            events = events.filter(
                Q(title__icontains=search) | Q(contentq__icontains=search)).distinct()
        if location:
            events = events.filter(location=location)
        # if time:
        #   events = events.filter(starter_date=time)

    paginator = Paginator(events, 1)
    try:
        events = paginator.page(page)
    except EmptyPage:
        events = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        events = paginator.page(1)

    context = {'events': events, 'form': form}
    return render(request, 'event/event_list.html', context)


@login_required(login_url='/user/login/')
def profile(request):
    user = Event.objects.filter(user=request.user)
    context = {
        "user": user
    }
    return render(request, 'profile.html', context)


@login_required(login_url='/user/login/')
def event_create(request):
    form = EventForm()
    if request.method == 'POST':
        form = EventForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
            msg = 'Tebrikler <strong> %s </strong> isimli gönderiniz başarı ile oluşturuldu.' % (event.title)
            messages.success(request, msg, extra_tags='success')
            return redirect('/events')
    return render(request, 'event/event-create.html', context={'form': form})


def event_detail(request, slug):
    form = CommentForm()
    event = get_object_or_404(Event, slug=slug)
    return render(request, 'event/event-detail.html', context={'event': event, 'form': form})


@login_required(login_url='/user/login/')
def event_update(request, slug):
    event = get_object_or_404(Event, slug=slug)
    if request.user != event.user:
        return HttpResponseForbidden
    form = EventForm(instance=event, data=request.POST or None,
                     files=request.FILES or None)  # bloğun içerisindeki değerleri çeker
    if form.is_valid():
        form.save()
        msg = 'Tebrikler %s isimli gönderiniz başarı ile güncellendi.' % (event.title)
        messages.success(request, msg, extra_tags='info')
        return HttpResponseRedirect(event.get_absolute_url())
    context = {'form': form, 'event': event}

    return render(request, 'event/event-update.html', context)


@login_required(login_url='/user/login/')
def event_delete(request, slug):
    event = get_object_or_404(Event, slug=slug)
    if request.user != event.user:
        return HttpResponseForbidden
    event.delete()
    return redirect('profile')


@login_required(login_url='/user/login/')
def registerEvent(request, slug):
    event = get_object_or_404(Event, slug=slug)
    event_member = EventMember.objects.filter(event=event, user=request.user)
    if not event_member.exists():
        EventMember.objects.create(event=event, user=request.user)
    return redirect('index')


def get_child_comment_form(request):
    data = {'form_html': ''}
    pk = request.GET.get('comment_pk')
    comment = get_object_or_404(NewComment, pk=pk)
    form = CommentForm()
    form_html = render_to_string('event/include/comment/comment-child-comment-form.html', context={
        'form': form,
        'comment': comment,
    }, request=request)

    data.update({
        'form_html': form_html
    })

    return JsonResponse(data=data)


def new_add_comment(request, pk, model_type):
    data = {'is_valid': True, 'event_comment_html': '', 'model_type': model_type}

    nesne = None
    all_comment = None
    form = CommentForm(data=request.POST)

    if model_type == 'event':
        nesne = get_object_or_404(Event, pk=pk)
    elif model_type == 'comment':
        nesne = get_object_or_404(NewComment, pk=pk)
    else:
        raise Http404

    if form.is_valid():
        icerik = form.cleaned_data.get('icerik')
        NewComment.add_comment(nesne, model_type, request.user, icerik)

    if model_type == "comment":
        nesne = nesne.content_object

    comment_html = render_to_string('event/include/comment/comment-list-partial.html', context={'event': nesne})

    data.update({
        'event_comment_html': comment_html
    })

    return JsonResponse(data=data)

ozgur_etkinlik/templates/event/event-create.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
Post Create
{% endblock %}


{% block ust_icerik %}


{% endblock %}


{% block icerik %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<link type="text/css" rel="stylesheet" href="{% static 'bootstrap-datetime/bootstrap-datetime.css' %}">
<script type="text/javascript" rel="script" src="{% static 'bootstrap-datetime/bootstrap-datetime.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker11').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>

<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <h1 class="page-header">Post Create</h1>
        <form action="{% url 'event-create' %}" enctype="multipart/form-data" method="post">
            {{ form.media }}


            {% csrf_token %}

            {% for field in form %}

            {% if field.name == 'starter_date' %}

            <div class="form-group">
                <label class="control-label">{{ field.label }}</label>

                <div class='input-group date' id='datetimepicker11'>
                    <input type='text' class="form-control"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            {% elif field.name == 'finish_date' %}

            <div class="form-group">
                <label class="control-label">{{ field.label }}</label>

                <div class='input-group date' id='datetimepicker12'>
                    <input type='text' class="form-control"/>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar">
                    </span>
                </span>
                </div>
            </div>

            {% else %}

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        <label class="control-label">{{ field.label }}</label>
                        {{ field }}

                        {% if field.errors %}
                        {% for error in field.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}

                        {% else %}
                        {% if field.help_text %}
                        <span class="text-success"> {{ field.help_text }}</span>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        <input type="submit" value="Kaydet" class="btn pull-right btn-sm btn-success">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}

ozgur_etkinlik/templates/event/event-detail.html
{% extends 'base.html' %}

{% block title %}
Post List
{% endblock %}


{% block ust_icerik %}

<script type="text/javascript">
    $(document).ready(function () {
        var $window = $(this);
        var $event_comment_list = $window.find('#event-comment-list');
        $window.on('submit', '.comment-form', function (e) {
            e.preventDefault();
            var $this = $(this);
            var $method = $this.attr('method');
            var $data = $this.serialize();
            var $url = $this.attr('action');

            $.ajax({

                url: $url,
                type: $method,
                dataType: 'json',
                data: $data,
                success: function (data) {
                    console.log(data.event_comment_html);

                    $event_comment_list.html(data.event_comment_html);
                    $this.find('#id_icerik').val('');


                },
                error: function () {
                    alert("Bir hata oluştu")
                }


            })
        });
        $window.on('click', '#event-comment-list div.row a.yanitla-button', function (e) {
            e.preventDefault();
            var $this = $(this);
            var $parent = $this.closest('div');
            var $href = $this.attr('href');
            var $comment_pk = $this.attr('comment_pk');
            $.ajax({
                url: $href,
                type: "GET",
                dataTyp: "json",
                data: {'comment_pk': $comment_pk},
                success: function (data) {
                    console.log(data);
                    var $form_html = data.form_html;
                    $parent.find('.child-form-container').html($form_html);
                },
                error: function () {

                }


            })
        })
    })

</script>

{% endblock %}


{% block icerik %}


<div class="row">
    <div class="col-lg-12">
        <div class="col-lg-8 col-lg-offset-2">
            <h2 class="page-header"><a href="{% url 'event-list' %}">
                <span class="glyphicon glyphicon-circle-arrow-left"></span></a> <a>{{ event.title|upper }}</a>

            </h2>
            <div class="row">
                <div class="col-lg-8">
                    <p><span class="glyphicon glyphicon-tree-deciduous"></span> <b>
                        Etkinlik Sahibi: <a
                            href="#">{{ event.user.userprofile.get_screen_name }}</a>
                    </b></p>
                    {% if event.image %}
                    <img class="img-responsive" src="{{ event.image.url }}" alt="">
                    {% endif %}
                </div>
                <div class="col-lg-4 ">

                    <p class="pull-left">{{ event.starter_date }}</p>
                    <br><br>
                    <p class="pull-left">{{event.city}} </p>
                    <br>

                    <a href="#" class="btn btn-success btn-block">Katıl</a>
                    <a href="#" class="btn btn-info btn-block">Favorilerilere ekle</a>
                    <a href="#" class="btn btn-default btn-block">Paylaş</a>

                    <hr>
                    <div style="height: 250px; width:250px; background-color:rosybrown"> HARİTA</div>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">

                    <span>{{event.content | safe}} </span>

                    <p class="lead">
                        Kategoriler: {{ event.kategoriler.all|join:',' }}
                    </p>
                </div>
            </div>
            {% if request.user == event.user %}
            <div class="row">
                <div class="col-lg-3 ">
                    <a href="{% url 'event-update' event.slug %}" class=" btn btn-primary">Güncelle</a>
                    <a href="{% url 'event-delete' event.slug %}" class=" btn btn-danger">Sil</a>
                </div>
            </div>
            {% endif %}


        </div>


    </div>
</div>

<div class="row pull-center">
    <h2 class="page-header">Yorumlar ({{ event.get_event_comment_count }})</h2>
    <div class="col-lg-10 col-lg-offset-2" id="event-comment-list">
        {% include 'event/include/comment/comment-list-partial.html' with event=event %}
    </div>
    <div class="row" style="margin-top: 50px;">

        <form class="comment-form" action="{% url 'new-add-comment' event.pk 'event' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="row">
                <div class="col-lg-2">
                    <div class="col-lg-12">
                        <img style="height:75px;" class=" img-circle"
                             src="{{ request.user.userprofile.get_profile_photo }}">
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <span class="text-danger"><b>{{ error }}</b></span>
                        {% endfor %}
                        {% else %}
                        {% if field.help_text %}
                        <span class="text-success"><b>{{ field.help_text }}</b></span>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <input type="submit" value="Yorum Yap" class="pull-right btn btn-success">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ozgur_etkinlik/templates/event/event-update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

{% endblock %}

{% block usticerik %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<link type="text/css" rel="stylesheet" href="{% static 'bootstrap-datetime/bootstrap-datetime.css' %}">
<script type="text/javascript" rel="script" src="{% static 'bootstrap-datetime/bootstrap-datetime.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker11').datetimepicker({});
        $('#datetimepicker12').datetimepicker({});
    });
</script>
{% endblock %}


{% block icerik %}

<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <h1 class="page-header">Post Update</h1>
        <form action="{% url 'event-update' event.slug %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% for field in form %}
            {% if field.name == 'starter_date' %}

            <div class="form-group">
                <label class="control-label">{{ field.label }}</label>

                <div class='input-group date' id='datetimepicker11'>
                    <input type='text' class="form-control"/>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar">
                    </span>
                </span>
                </div>
            </div>
            {% elif field.name == 'finish_date' %}

            <div class="form-group">
                <label class="control-label">{{ field.label }}</label>

                <div class='input-group date' id='datetimepicker12'>
                    <input type='text' class="form-control"/>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar">
                    </span>
                </span>
                </div>
            </div>

            {% else %}
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        <label class="control-label">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}

                        {% else %}
                        {% if field.help_text %}
                        <span class="text-success"> {{ field.help_text }}</span>
                        {% endif %}
                        {% endif %}

                    </div>
                </div>
            </div>
            {% endif %}

            {% endfor %}
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        <input type="submit" value="Güncelle" class="btn pull-right btn-sm btn-success">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}

ozgur_etkinlik/templates/event/event_list.html
{% extends 'base.html' %}

{% block title %}
Event List
{% endblock %}

{% block ust_icerik %}

{% endblock %}


{% block icerik %}

<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">
                <form class="form-inline" action="{% url 'event-list' %}">

                    {% for foo in form %}
                    <div class="form-group">
                        {{ foo }}
                        {% for error in foo.errors %}
                        <span class="text-danger"><b>{{ error }}</b></span>
                        {% endfor %}
                    </div>

                    {% endfor %}

                    <input type="submit" class="btn btn-success" value="Ara">

                </form>

            </div>

        </div>


        {% for event in events %}

        <div class="col-lg-3 pull-left">
            <h3><a href="{% url 'event-detail' event.slug %}"> {{ event.title }}</a></h3>

            {% if event.get_image %}
            <img width="275" height="208" class="img-responsive" src="{{ event.get_image }}" alt="">

            {% endif %}

            <p> Başlangıç tarihi: {{event.starter_date}}</p>

            <a href="#" class="btn btn-info">Favorilere Etkinliklerime Ekle</a>

            <p>Etkinliği oluşturan: <a href="#"> {{event.user}}</a></p>


        </div>
        {% empty %}

        <p class="alert alert-info">Aradağınız Kiriteder Bir Blog Bulunamadı</p>

        {% endfor %}

        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-8 col-lg-offset-2">
                    {% if events.has_other_pages %}
                    <ul class="pagination">
                        {% if events.has_previous %}
                        <li><a href="?page={{ events.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in events.paginator.page_range %}
                        {% if events.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if events.has_next %}
                        <li><a href="?page={{ events.next_page_number }}">&raquo;</a></li>
                        {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}